### PR TITLE
Add nightly tests

### PR DESCRIPTION
**Pull request by phackstock**
Title captures most of it. 
For now I just copied the content of `.github/workflows/test.yaml` and changed `on:` to a scheduled build. 
In analogy to [`pyam`](https://github.com/iamconsortium/pyam) I scheduled the build for every Tuesday at 4 am.

Looking forward to your thoughts on setup or schedule/frequency.

### CODE REVIEW

**Comment by khaeru** [comment]
> copied the content of `.github/workflows/test.yaml` and changed `on:` to a scheduled build.

It's possible to include both `scheduled:` and other entries under `on:`; see for example [here](https://github.com/khaeru/sdmx/blob/d871e045f5bc163b83750b32bf22b5ac4cdebfc0/.github/workflows/pytest.yaml#L3-L9). This is preferable than duplicating a file, as the copies might then grow out of sync or must be (visually) diff'd over and over to prevent that.

**Comment by phackstock** [comment]
Ah nice, sure I'll add `scheduled` to `test.yaml` and remove `nightly.yaml`. Any preference on the schedule and/or frequency (e.g. once a day, week, etc...)?

**Comment by khaeru** [comment]
> I'll add `scheduled` to `test.yaml` and remove `nightly.yaml`.

Please rebase on `main` when you do, to pick up changes from #35.

**Comment by phackstock** [comment]
Rebased on latest version of `main`

**Comment by phackstock** [comment]
Looking into this here's what I've found our various other packages do:
* `ixmp`: Daily at 5 am
* `message_ix`: Also daily at 5 am (with a dedicated nightly test)
* `pyam`: Every Tuesday at 5 am

What do you think @khaeru, should I stick with every day at 5 am?

**Comment by khaeru** [comment]
5:00 UTC sounds good.

**Comment by phackstock** [comment]
Updated

**Review by khaeru — APPROVED** [review]
Thanks. Will merge once checks pass.

**Comment by phackstock** [comment]
Perfect, thanks

**Pull request merged**
